<?php
/**
*@file
*Event Log File Module
*@author SURAJ KOTHAWADE <kothawadesuraj@sggs.ac.in> 
*/
/**
*Implementation of hook_permission
*/
function event_log_file_permission() {
  return array(
    'administer event_log_file' => array(
      'title' => t('Administer Event Log File'),
      'description' => t('Perform administration tasks for file log.'),
    ),
  );
}
/**
*Implementation of hook_menu
*/
function event_log_file_menu() {
   $items['admin/config/event_log_file'] = array(
  'title' => 'File Log Settings',
  'type' => MENU_NORMAL_ITEM,
  'page callback' => 'drupal_get_form',
'page arguments'=>array('event_log_file_admin_form'),
'access arguments'=>array('administer event_log_file'),
  );
return $items;
}
/**
*Implementation of event_log_delete_admin_form
*@param $form :associative array to contain information related to form elements.
*@param $form_state :associative array contaning values realted to elemnts in the form.
*@return $form   :associtaive array which has information to form elements. 
*/
function event_log_file_admin_form($form ,&$form_state) {
  
$form['event_log_file_enable'] = array(

  '#type' =>'checkbox', 

  '#title' => t('Save Logs in File'),

  '#default_value' => variable_get('event_log_file_enable',0),
  '#description' => t('<strong>WARNING : Enabling this feature will not notify the user about illegal login to their accounts.</strong>')
);
    return system_settings_form($form);

}
?>
