<?php
/**
* implementataion OF hook_permission
*/
function log_data_visualization_analysis_permission() {
  return array(
    'access viz' => array(
      'title' => t('Administer Viz'),
      'description' => t('Access administration viz on my site.'),
    ),
    'access vizone' => array(
      'title' => t('Administer Vizone'),
      'description' => t('Access administration vizone on my site.'),
    ),
    'access viztwo' => array(
      'title' => t('Administer Viztwo'),
      'description' => t('Access administration viztwo on my site.'),
    ),
    'access vizthree' => array(
      'title' => t('Administer Vizthree'),
      'description' => t('Access administration vizthree on my site.'),
    ),
    'access config' =>array(
      'title'=>t('Configuration page'),
      'description'=>t('Access configuration Page for log analysis'),
      ),
  );
}
/**
* implementation of hook_menu
*/

function log_data_visualization_analysis_menu() {
   $items['viz'] = array('title' => 'Event Log Visualizations',
    'description' => 'Different event log visualizations using d3.',
    'page callback' => 'log_data_visualization_analysis_linegraph',
    'access arguments' => array('access viz'),
    );
   $items['viz/vizone'] = array(
      'title' => 'Line graph',
    'description' => 'Uses d3 module to create a line graph',
    'access callback' => TRUE,
    'page callback' => 'log_data_visualization_analysis_linegraph',
    'type' => MENU_DEFAULT_LOCAL_TASK,    );
   $items['viz/viztwo'] = array(
          'title' => 'Bar chart',
    'description' => 'Uses d3 module to create a bar chart',
    'access callback' => TRUE,
    'page callback' => 'log_data_visualization_analysis_bar',
    'type' => MENU_LOCAL_TASK,    );
   $items['viz/vizthree'] = array(
          'title' => 'Pie chart',
    'description' => 'Uses d3 module to create a pie chart.',
    'access callback' => TRUE,
    'page callback' => 'log_data_visualization_analysis_pie',
    'type' => MENU_LOCAL_TASK,
    );

   $items['admin/config/log_data_visualization_analysis']=array(
    'title'=>'Config page for log analysis',
    'page callback' => 'drupal_get_form',
'page arguments'=>array('log_data_visualization_analysis_admin_form'),
    'access arguments'=>array('access config'),
    );
    return $items;
}

function log_data_visualization_analysis_admin_form($form ,&$form_state) {
      $form['submit_button'] = array(
  '#type' => 'submit',
  '#value' => t('Go to Visualizations'),
  '#submit' => array('log_data_visualization_analysis_select'),
  );
    return $form;
  }
function log_data_visualization_analysis_select($form,&$form_state)
{  
  drupal_goto('viz');
}
function log_data_visualization_analysis_linegraph() {
 
  $leg_aux=array();
  $query2="Select distinct(operation) from event_log ";
  $k=1;
  $operate=array();
  $operatio=db_query($query2);
  $operations=$operatio->fetchAll(PDO::FETCH_ASSOC);
  if(count($operations)==0)
   return "<strong>No Log Data</strong>";
  foreach ($operations as $row) {
    $leg_aux[strval($row['operation'])]=$k++;
    }
  $leg=array();
  foreach ($leg_aux as $key => $value) {
    array_push($leg,strval($key));
    
  }
  $query="Select operation, created from event_log ";
  $result=db_query($query);
  $results=$result->fetchAll(PDO::FETCH_ASSOC);
  $arr=array();
  $final_line=array();
  $h=0;
  $prev="q";
  
  foreach ($results as $row) {
    $h++;
    $curop=$row['operation'];
      $curmonth=strval(date("M-Y",$row['created']));
  
    if($curmonth!=$prev)
      {
         
        if($h!=1)
          array_push($final_line,$arr);
        
        $arr[0]=$curmonth;
        for($i=1;$i<$k;$i++)
          $arr[$i]=0;
        $arr[$leg_aux[$curop]]++;
      }
      else 
      {
          $arr[$leg_aux[$curop]]++;
      }

      $prev=$curmonth;
  
  }
  array_push($final_line, $arr);
  
  $chart = array(
    'id' => 'visualization',
    'type' => 'linegraph',
    'legend' => $leg,
    'rows' =>$final_line,
  );

  return d3_draw($chart);
}
function log_data_visualization_analysis_column() {

  
  return d3_draw($chart);
}

/**
 * Generates a random example bar graph.
 *
 * @return string
 *   HTML for the page content.
 */
  function log_data_visualization_analysis_bar() {

  $query = db_query("SELECT operation, count(*) FROM {event_log} GROUP BY operation");
  $result = $query->fetchAll(PDO::FETCH_ASSOC);
  $newarray=array();
 if(count($result)==0)
  return "<strong>No Log Data</strong>";
  foreach($result as $row)
  {
             array_push($newarray,array($row['operation'],$row['count(*)']));
                 
  }
  
  $chart = array(
    'id' => 'visualization',
    'type' => 'barchart',
    'legend' => array(
      'Operations',
    ),
    'rows' => $newarray,
  );

  
  return d3_draw($chart);
}

/**
 * Generates a random pie chart example.
 *
 * @return string
 *   HTML for the page.
 */
function log_data_visualization_analysis_pie() {
  $query='SELECT uid,count(operation) FROM event_log GROUP BY uid';
  $result=db_query($query);
  $results= $result->fetchAll(PDO::FETCH_ASSOC);   
   if(count($results)==0)
  return "<strong>No Log Data</strong>";
  $ar=array();
  $final_ar=array();
  $query2='SELECT * FROM users';
  $users = array();
  $temp=array();
  $userresult=db_query($query2);
  $userresults=$userresult->fetchAll(PDO::FETCH_ASSOC);
    
  foreach ($userresults as $row) {
    if($row['uid']==0)
      $users[$row['uid']]='Anonymous';
    else $users[$row['uid']]=strval($row['name']);
      
    } 
  foreach($results as $res) {
    $ar[0]=strval($users[$res['uid']]);
    $ar[1]=$res['count(operation)'];
    array_push($final_ar,$ar);
  }
  $chart = array(
    'id' => 'visualization',
    'type' => 'piechart',
    'rows' => $final_ar,
  );
  return d3_draw($chart);
}


?>

