<?php
/**
*implements hook_permission
*/
function log_data_visualization_user_permission() {
  return array(
    'access vizu' => array(
      'title' => t('Administer User'),
      'description' => t('Access administration user on my site.'),
    ),
'access vizactive' => array(
      'title' => t('Administer User'),
      'description' => t('Access administration user on my site.'),
    ),
    'access user' => array(
      'title' => t('Administer User Event Analysis'),
      'description' => t('Access administration for user versus operation analysis.'),
    ),
  );
}

/**
*implements hook_menu
*/
function log_data_visualization_user_menu() {
    $items['vizu'] = array('title' => 'User Event Analysis',
    'description' => 'Different event log visualizations using d3.',
    'page callback' => 'log_data_visualization_user_pie',
    'access arguments' => array('access vizu'),
    );
  $items['vizactive'] = array('title' => 'Active User Event Analysis',
    'description' => 'Top Active Users.',
    'page callback' => 'log_data_visualization_user_active',
    'access arguments' => array('access vizactive'),
    ); 
   $items['admin/config/log_data_visualization_user']=array(
    'title'=>'Configuration page for log analysis',
    'page callback' => 'drupal_get_form',
	'page arguments'=>array('log_data_visualization_user_admin_form'),
    'access arguments'=>array('access user'),
    );


    return $items;
}

function log_data_visualization_user_admin_form($form ,&$form_state) {
    
  $form['enter_number'] = array(
  '#title' => t('Enter number of Users '),
  '#type' => 'textfield',
  '#description' => t('This text area where admin enter number of top active user'),
  '#default_value' => '',
   );
  $form['number_button'] = array(
  '#type' => 'submit',
  '#value' => t('Submit Number'),
  '#submit' => array('log_data_visualization_user_select_number'),
  );
   
  $form['enter_user'] = array(
    '#title' => t('Enter User'),
    '#type' => 'textfield',
    '#description' => t('This text area where admin enter name of user'),
    '#default_value' => '',
    );

   $form['submit_button'] = array(
    '#type' => 'submit',
    '#value' => t('Submit User'),
    '#submit' => array('log_data_visualization_user_select'),
  );
    return $form;

  }

function log_data_visualization_user_select($form,&$form_state)
{ 
  $user=$form_state['values']['enter_user'];
   $query = "SELECT uid FROM {users} WHERE name='".$user."'";
$result=db_query($query); 
 $results=$result->fetchAll(PDO::FETCH_ASSOC);
if(count($results)>0)
  $user=$results[0]['uid'];
  $arg=array('query'=>array('userid'=>$user,),);
  drupal_goto('vizu',$arg);
  }
  

function log_data_visualization_user_pie() {
if(isset($_GET['userid']))
	$var=intval($_GET['userid']);
else 
	$var=1;
$auth='authentication';
$query = "SELECT operation,count(operation) FROM `event_log` WHERE uid=".$var." and type!='authentication' group by operation";

  $result=db_query($query);
  $ar=array();
  $final_ar=array();
  $results=$result->fetchAll(PDO::FETCH_ASSOC);
  if(count($results)==0)
  	return "<strong>No Log Data</strong>";
  foreach($results as $res) {
    $ar[0]=strval($res['operation']);
    $ar[1]=$res['count(operation)'];
    array_push($final_ar,$ar);
  }
  
    $chart = array(
    'id' => 'visualization',
    'type' => 'piechart',
    'rows' => $final_ar,
      );
  return d3_draw($chart);
  
}
function log_data_visualization_user_select_number($form,&$form_state)
{ 
  $user=$form_state['values']['enter_number'];
   $user=intval($user);
  $arg=array('query'=>array('usernum'=>$user,),);
  drupal_goto('vizactive',$arg);
  }
function log_data_visualization_user_active()
{
if(isset($_GET['usernum']))
	$var=intval($_GET['usernum']);
else 
	$var=1;

$query="SELECT u.name as name, t.ucount as co FROM (select e.uid as uid ,count(*) as ucount from event_log as e group by e.uid ) as t , users as u WHERE u.uid=t.uid order by t.ucount desc limit ".strval($var);
 $result=db_query($query);
 $result=$result->fetchAll(PDO::FETCH_ASSOC);
$query="SELECT count(*) as cou FROM event_log";
$count=db_query($query);
 $count=$count->fetchAll(PDO::FETCH_ASSOC);
$totalcount=$count[0]['cou'];
$iter=count($result);
for($i=0;$i<$iter;$i++)
{
  $result[$i]['co']=round(($result[$i]['co']*100)/$totalcount);
  if($result[$i]['name']=='')
     $result[$i]['name']='Anonymous';
}
$header=array('USER','% Usage');
$render_array['maintable'] = array(
  '#theme' => 'table',
  '#header' => $header,
  '#rows' => $result,
);
return $render_array;

 
}
?>


