<?php
/**
*@file
*cron monitor module
*/
/**
*implementation of hook permission
*/
function deletelog_permission() {
  return array(
    'administer deletelog' => array(
      'title' => t('Administer Delete Log'),
      'description' => t('Perform administration tasks for delete log.'),
    ),
  );
}
/**
*implemenatation of hook_menu
*/
function deletelog_menu() {
   $items['admin/config/deletelog'] = array(
  'title' => 'Delete log settings',
  'type' => MENU_NORMAL_ITEM,
  'page callback' => 'drupal_get_form',
'page arguments'=>array('deletelog_admin_form'),
'access arguments'=>array('administer deletelog'),
  // Page callback, etc. need to be added here.
);
return $items;
}
/**
* implementation of delete log admin form
*/
function deletelog_admin_form($form ,&$form_state) {
      $form['deletelog_button'] = array(
  '#type' => 'submit',
  '#value' => t('Delete Logs'),
  '#submit' => array('deletelog_deletedb'),
);

  /* $form['cronmonitor_email_text'] = array(
  '#title' => t('Text to send with Cron Monitor'),
'#type' => 'textarea',
'#description' => t('Enter some text to send To send with Cron Monitor Email'),
'#default_value' => variable_get('cronmonitor_email_text',''),
);
*/
     // deletelog_deletedb();
//    drupal_cron_run();
    return system_settings_form($form);

}
/**
**
* Deleltion of event_log table
**
**/
function deletelog_deletedb(){
//if(variable_get('deletelog_enable',0))
  //  {
           //          variable_set('deletelog_enable',0);
         $query="delete from event_log;";
         db_query($query);
    //}  

}
/**
* implementation of hook cron
*/

/*function deletelog_cron() {
   if(variable_get('deletelog_enable',0))
    {
                     variable_set('deletelog_enable',0);
         $query="delete from event_log;";
         db_query($query);
  
  }
}
*/
/**
*implementation of hook mail
*/

/*function cronmonitor_mail($key, &$message, $params) {
  switch($key)
  {
           case 'cronmonitor_email':
    $message['subject']=t('This is Cron Monitor Report');
    $message['body'][]=t('This is report from cron monitr on @site-name ',array('@site-name'=>variable_get('site-name','sumedha site')));
    $message['body'][]=t(variable_get('cronmonitor_email_text',''));
    
                break;

  }
}*/
?>
