<?php
/**
*@file
*Event Log Delete Module
*@author Akskay sharma <akshay31057@gmail.com>
*/
/**
*Implementation of hook_permission
*/
function event_log_delete_permission() {
  return array(
    'administer event_log_delete' => array(
      'title' => t('Administer Event Log Delete'),
      'description' => t('Perform administration tasks for delete log.'),
    ),
  );
}
/**
*Implemenatation of hook_menu
*/
function event_log_delete_menu() {
   $items['admin/config/event_log_delete'] = array(
  'title' => 'Delete log settings',
  'type' => MENU_NORMAL_ITEM,
  'page callback' => 'drupal_get_form',
'page arguments'=>array('event_log_delete_admin_form'),
'access arguments'=>array('administer event_log_delete'),
);
return $items;
}

/**
*Implementation of event_log_delete_admin_form
*@param $form :associative array to contain information related to form elements.
*@param $form_state :associative array contaning values realted to elemnts in the form.
*@return $form   :associtaive array which has information to form elements. 
*/

function event_log_delete_admin_form($form ,&$form_state) {
      $form['event_log_delete_button'] = array(
  '#type' => 'submit',
  '#value' => t('Delete Logs'),
  '#submit' => array('event_log_delete_deletedb'),
);

    return system_settings_form($form);
}
/**
*
*Implementation of event_log_delete_deletedb
*Delete all entries in event_log table from drupal database.
*/
function event_log_delete_deletedb(){
         $query="delete from event_log;";
         db_query($query);

}
?>
