<?php
/**
*@file
*cron monitor module
*/
/**
*implementation of hook permission
*/
function deletelog_permission() {
  return array(
    'administer deletelog' => array(
      'title' => t('Administer Delete Log'),
      'description' => t('Perform administration tasks for delete log.'),
    ),
  );
}
/**
*implemenatation of hook_menu
*/
function deletelog_menu() {
   $items['admin/config/deletelog'] = array(
  'title' => 'Delete log settings',
  'type' => MENU_NORMAL_ITEM,
  'page callback' => 'drupal_get_form',
'page arguments'=>array('deletelog_admin_form'),
'access arguments'=>array('administer deletelog'),
  // Page callback, etc. need to be added here.
);
return $items;
}

/**
* implements delete log admin form
*/

function deletelog_admin_form($form ,&$form_state) {
      $form['deletelog_button'] = array(
  '#type' => 'submit',
  '#value' => t('Delete Logs'),
  '#submit' => array('deletelog_deletedb'),
);

    return system_settings_form($form);

}

/**
*
* Implements  Deleltion of event_log table
*
*/
function deletelog_deletedb(){
         $query="delete from event_log;";
         db_query($query);

}
?>
