<?php
/**
*@file
*cron monitor module
*/
/**
*implementation of hook permission
*/
function event_log_delete_permission() {
  return array(
    'administer event_log_delete' => array(
      'title' => t('Administer Event Log Delete'),
      'description' => t('Perform administration tasks for delete log.'),
    ),
  );
}
/**
*implemenatation of hook_menu
*/
function event_log_delete_menu() {
   $items['admin/config/event_log_delete'] = array(
  'title' => 'Delete log settings',
  'type' => MENU_NORMAL_ITEM,
  'page callback' => 'drupal_get_form',
'page arguments'=>array('event_log_delete_admin_form'),
'access arguments'=>array('administer event_log_delete'),
);
return $items;
}

/**
* implements delete log admin form
*/

function event_log_delete_admin_form($form ,&$form_state) {
      $form['event_log_delete_button'] = array(
  '#type' => 'submit',
  '#value' => t('Delete Logs'),
  '#submit' => array('event_log_delete_deletedb'),
);

    return system_settings_form($form);
}
/**
*
* Implements  Deletion of event_log table
*
*/
function event_log_delete_deletedb(){
         $query="delete from event_log;";
         db_query($query);

}
?>